---
name: Docker Build and Upload

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches: [master]
  pull_request:
  schedule:
    # once a week
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        # Required only for the multi-arch container builds
        # that are pushed to Dockerhub.
        # Setting up QEMU during normal PRs prevents testing
        # of the container included
        # QEMU setup.
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            catdevsecops/packer-builder-arm
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=v(.*),group=1

      #### build+export, test only on PRs
      - name: Build and export to Docker
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: packer-builder-arm:test
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install packer plugins
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build \
          packer-builder-arm:test init \
          boards/raspberry-pi-4/ubuntu_server_20.04_arm64.pkr.hcl

      - name: Test build board
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm --privileged -v /dev:/dev \
          -v ${PWD}:/build packer-builder-arm:test build \
          boards/raspberry-pi-4/ubuntu_server_20.04_arm64.pkr.hcl  \
          -extra-system-packages=bmap-tools,zstd
          du -h ubuntu-20.04.img
          du -h --apparent-size ubuntu-20.04.img


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
