---
name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cache
        id: cache-key
        uses: actions/cache@v4
        with:
          path: packer-builder-arm
          key: key-${{ github.sha }}-1

      - name: Checkout
        if: steps.cache-key.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.1

      - name: Set up Go 1.21
        if: steps.cache-key.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
        id: go

      - name: Get dependencies
        if: steps.cache-key.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        if: steps.cache-key.outputs.cache-hit != 'true'
        run: go build -v .

      - name: Cache binary
        if: steps.cache-key.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: packer-plugin-arm
          key: key-${{ github.sha }}-1

  test:
    needs: compile
    strategy:
      fail-fast: false
      matrix:
        boards:
          - beaglebone-black/angstrom.json
          - beaglebone-black/archlinuxarm.json
          - beaglebone-black/debian.json
          - odroid-u3/archlinuxarm.json
          - odroid-xu4/archlinuxarm.json
          # - odroid-xu4/ubuntu.json
          # - parallella/archlinuxarm.json
          - parallella/ubuntu.json
          # - raspberry-pi/archlinuxarm.json
          - raspberry-pi/raspbian.json
          - raspberry-pi/raspbian-resize.json
          - raspberry-pi/raspios-lite-arm.json
          # - raspberry-pi-3/archlinuxarm.json
          - raspberry-pi-3/raspios-lite-arm64.json
          - raspberry-pi-4/ubuntu_server_20.04_arm64.json
          - raspberry-pi-4/ubuntu_server_20.04_arm64.pkr.hcl
          # - raspberry-pi-4/archlinuxarm.pkr.hcl
          - rock-4b/debos-radxa.pkr.hcl
          # - wandboard/archlinuxarm.json
    name: Build ${{ matrix.boards }} image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Fetch additional packages
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static \
          libarchive-tools tar binfmt-support qemu-utils

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v3
        with:
          packer-version: 1.10.3

      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: packer-plugin-arm
          key: key-${{ github.sha }}-1

      - name: Restore Packer Path
        id: restore-packer-path-sudo
        run: |
          echo "packer-path=$(whereis packer | awk '{print $3}')" \
          >> $GITHUB_OUTPUT

      - name: Install packer plugins
        if: ${{ endsWith(matrix.boards, '.hcl') }}
        run: PACKER_LOG=1 packer init boards/${{ matrix.boards }}

      - name: Validate
        run: PACKER_LOG=1 packer validate boards/${{ matrix.boards }}

      - name: Build image
        run: |
          PACKER_LOG=1 sudo \
          ${{ steps.restore-packer-path-sudo.outputs.packer-path }} \
          build boards/${{ matrix.boards }}

  plugin-check:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19
      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: packer-plugin-arm
          key: key-${{ github.sha }}-1
      - name: check
        run: |
          make plugin-check
